---



# Install Selinux management packages on the all targeted hosts
- hosts: all
  gather_facts: false
  become: true
  tasks:
      # required to repo manipulation
    - name: Install libselinux-python
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - policycoreutils-python
        - libselinux-python

# Setup Selinux permissions for the Nginx
- hosts: nginx
  gather_facts: false
  become: true
  tasks:
    - name: Enable tcp/8000 in selinux
      seport:
        ports: "8000"
        proto: tcp
        reload: yes
        state: present
        setype: http_port_t

# Setup iptables permissions for the Nginx
- hosts: nginx
  gather_facts: false
  become: true
  tasks:
    - name: Setup iptables permissions for the Nginx
      iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: tcp
        destination_port: "80"
        comment: 'Accept all nginx traffic'


# Setup Haproxy permissions for the HAproxy
- hosts: haproxy
  gather_facts: false
  become: true
  tasks:
    - name: Enable tcp/80 in selinux
      seport:
        ports: "80"
        proto: tcp
        reload: yes
        state: present
        setype: http_port_t

# Setup iptables permissions for the Nginx
- hosts: nginx
  gather_facts: false
  become: true
  tasks:
    - name: Setup iptables permissions for the Nginx
      iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: tcp
        destination_port: "{{ http_port }}"
        comment: 'Accept all nginx traffic'

# Setup Nginx virtualhosts
- hosts: nginx
  gather_facts: true
  become: true
  vars:
    www_dir: "/var/www"
  roles:
    - role: geerlingguy.nginx
      nginx_vhosts:
        - listen: "8000 default_server"
          server_name: "{{ inventory_hostname }}"
          root: "{{ www_dir }}"
          index: "index.php index.html index.htm"
          extra_parameters: |
            location = /probe_local {
              rewrite ^/probe_local$ /local.html;
              break;
            }
            location = /probe_applicant {
              rewrite ^/probe_applicant$ #/probe_applicant;
              break;
            }
            location = /probe_remote {
              proxy_pass http://localhost:5500;
              break;
            }
            location / {
              proxy_pass http://google.com;
            }

# Check/create all Nginx-related directories
  tasks:
    - name: ensure www_dir exists
      file:
        path: "{{ www_dir }}"
        state: directory

    - name: Templating local.html
      template:
        src: local.html.j2
        dest: "{{ www_dir }}/local.html"

    - name: Copy /probe_applicant
      copy:
        src: probe_applicant
        dest: "{{ www_dir }}/probe_applicant"

# Setup HAproxy with the Ansible Galaxy hole
- hosts: haproxy
  become: true
  gather_facts: true
  roles:
    - role: geerlingguy.haproxy
      haproxy_frontend_name: 'testfrontend'
      haproxy_frontend_bind_address: '*'
      haproxy_frontend_port: 80
      haproxy_frontend_mode: 'http'
      haproxy_backend_balance_method: 'roundrobin'
      haproxy_backend_httpchk: 'GET /probe_local'
      haproxy_backend_servers:
        - name: "{{ hostvars[groups['nginx'][0]].inventory_hostname }}:8000"
          address: "{{ hostvars[groups['nginx'][0]].ansible_eth0.ipv4.address }}:8000"
        - name: "{{ hostvars[groups['nginx'][1]].inventory_hostname }}:8000"
          address: "{{ hostvars[groups['nginx'][1]].ansible_eth0.ipv4.address }}:8000"

# Tuning sysctl
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Tuning sysctl
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { key: net.core.somaxconn, value: 65536 }
        - { key: net.ipv4.tcp_max_tw_buckets, value: 1440000 }
        - { key: net.ipv4.ip_local_port_range, value: "1024 65535" }
        - { key: net.ipv4.tcp_fin_timeout, value: 15 }
        - { key: net.ipv4.tcp_window_scaling, value: 1 }
        - { key: net.ipv4.tcp_max_syn_backlog, value: 3240000 }
